igdmapps/igdm

browser/js/funcs.js
Hey, I am Chinese user, I found that when I need to choose the candidate word, the keyup event will be trigger, so I change the event of the key code 13 (Enter) .
Below is the case of the Chinese input problem
=> replace "keyup" to "keypress" for chinese input (keycode 13)

package.json
Hi,
You are currently using your own fork of instagram-private-api that you haven't modified (it's just a fork). 
However the development of this module is still maintained by the community and should be used instead of your fork. 
I think using their repo would solve the issues some users had trying to connect to IG. 
Tested the app with this version, works well.
=> More Maintained IG API

.travis.yml, README.md
This add's Travis support (obviously you will need to synchronize your account with Travis before).
I think this is necessary because you ship it as an end user app, thus at least ensure security for dependencies with `npm audit`. Of course you should also add unit tests with e.g `mocha`, but that's another bottle to open up.
=> [travis] Add travis support

package.json
Hey @ifedapoolarewaju I work on the Snapcraft team and would love to help get igdm published in the [Snap Store](https://snapcraft.io/store), which is the app store for Linux :smiley: This pull request adds a snap to the Linux builds.
Once published, you'll have direct control of the publishing life cycle, access to metrics for weekly active devices and users will get automatic updates. I see you're using Travis, here are the docs for publishing in the Snap Store.
* https://docs.snapcraft.io/releasing-to-the-snap-store/6848
* https://docs.travis-ci.com/user/deployment/snaps/
I'd love to feature igdm as an editors pick in the store and put together a social campaign to promote it. Is there any other help you need to get igdm published in the snap store?
=> Publish igdm in the Snap Store for Linux

browser/js/index.js
The existing menu text for sending/not sending SEEN receipts is ambiguous.  This pull request is to help resolve that by clearly stating what the current state is.
The confusion being when the menu reads 'SEND "SEEN" RECEIPTS' a user may be unclear if that mean the current state is to send seen receipts, or they need to click the item to switch to sending seen receipts.
'Don't send "Seen" receipts' becomes 'Send "SEEN" Receipts - currently enabled'
'SEND "SEEN" RECEIPTS' becomes 'Send "SEEN" Receipts - currently disabled'
Thanks!
=> Clarified description of SEEN Receipt menu text

browser/js/renderers.js
I looked at my personal chat history for `animated_media` message types and found that all instances of these types contained an animated gif. I'm suggesting following changes based on the same assumption.
Please review!
=> add animated_media message renderer

browser/css/app.css, browser/js/index.js, browser/js/renderers.js, main/instagram.js, main/main.js
Please review these changes.
I also have a follow-up. A message-reaction event is stored in chat history with message type `actionLog` which is currently rendered as `<unsupported message format>`. Can I make a commit to avoid rendering these messages?
=> Render likes on messages

browser/js/renderers.js, package-lock.json, package.json
Resolve #996 
Voice media messages are being displayed as unsupported message format.
In order to add support for this kind of message a new renderer was added. Now it's possible to listen to voice messages and even download them.
=> add support for voice media

browser/js/funcs.js, browser/js/renderers.js
Currently, IGDM uses a comma-separated list of the usernames in a group chat as its title instead of the group chat's actual name. This pull request fixes that.
=> Show proper titles for group chats

browser/js/index.js
Due to using Chromium, the client could drag and drop an image, video or audio and IGDM would exit the window and starting play it, with no way of getting back to main screen.
Thus, I disabled the option to drag and drop.
However, I think a nicer implementation would be using drag and drop to send images or videos, but I don't have enough programming skills to code that.
=> Disabled Drag and Drop

browser/js/renderers.js
makes it easier to understand if someone sent a disappearing photo or tried to start a call
=> adding type to the unsupported messages

browser/js/funcs.js, browser/js/renderers.js
Images from instagram api are received as jpg.
Steps to download :
1. Right click on any image (.jpg/.jpeg) file.
2. Click on 'Save image as...'
3. Select the path to save.
Closes: #1225
Preview:
=> Easy save image on pc

browser/js/funcs.js
Closes: #1129 
After sending the message the text area remained the same size.
**Steps:**  
1. A **New Event** of "input" should be dispatched in the _element/text-area_ when we reset the text which will resize textarea.
=> Reset text area after message is sent

browser/css/app.css, browser/js/carousel.js, browser/js/funcs.js, browser/js/renderers.js
If we share a post with mutliple mediatype, i.e. post containing images/videos. _Videos_ are not rendered when we click on the post which renders in **Carousel**.
**As explained in the issue : #1210** 
Closes: #1210
=> Play Video in a carousel. 

main/main.js, main/menutemplate.js, main/storage.js, main/userpreferences.js
**Feature:** Enable/Disable check for auto-update.
**Description:** Auto-update to the new release is always _ON_ by default. This feature checks saved user-preference and updates only when Auto-update is enabled. 
**Preview:**
__** WHATS NEW ? **__
**Storage API:** Introducing to storage.js which can help developer to store user preferences and can create new store to save/preserve data specific to each user.  
Closes: #1240 , #444
=> [Feat] Optional update of IG:dm

browser/js/funcs.js, browser/js/globals.js, browser/js/index.js, browser/js/renderers.js, main/main.js
Closes: #1255 
**Issue:**
When we send multiple messages we render for each message sent, which occurs in all the message to take appear at once.
**Fix**
Track when to re-render the chat screen.
**Preview**
=> [Fix] Rendering issue while sending multiple messages in short delay

browser/css/app.css, browser/js/funcs.js, browser/js/index.js, browser/js/renderers.js, gulpfile.js, main/instagram.js, main/main.js, main/utils.js, package-lock.json, package.json
**- Updating to the latest "instagram-private-api" repository (migration)**
**- Updating Two-Factor-Authentication (fix)**
_After entering the code in the OTP window, still login was not happening_
**- Send Image in chat (fix)**
_We were not able to send .jpg images in the chat previously. Fixed the issue_
**- Chat gets stuck while loading old messages when reaches last message (fix)**
_When we go to the very top of the chat, when there is no more old messages, the chat seems to be stuck there sometimes_
**- Limiting image height in chat view (update)**
_The image renders with the original size, which captures a lot of space of the chat screen, limited the height to 300px for better chat view_
Closes: #1245 , #1244, #1243 , #1241
=> [Migration] Upgrade to new version of Instagram APIs

browser/js/renderers.js
This got broken after last release, so fixing the update from `visualMedia` to `visual_media`
=> fix raven image (pics from phones)

browser/css/app.css
Minor fix to make the "seen" tag be showed on the right side of the screen, as the official app does. Currently they're showed on the left side, as they were related to the othe person's messages.
=> Seen tag shown on right side

browser/css/app.css, browser/js/renderers.js
Issue : 
`.viewer .content img / video` has `height: 100vh;` which affects the view of image of users too for **users-not-following** section.
Preview: 
Fix: 
made new class "full-screen" for individual image/video to load them full screen :D
=> [UI-Fix] Css change for User-not-following back view

browser/css/app.css, browser/js/funcs.js, browser/js/renderers.js, main/instagram.js, main/main.js
Few of the Instagram accounts don't support `presence.last_activity_at_ms` even when `chat_.presence` is an Object.
Issue while rendering chat for that account:
1. Unable to open those chats which have `null` value for` presence.last_activity_at_ms`
UI-Fixes:
1. The text are rendering in big size, and taking extra header.
Updated:
=> [Fix] Null check required under User.Presence Object

main/main.js, main/menutemplate.js
Refactor the createTemplate function to accept a base template. With the change, we can pass the default base menu on dev and extend by adding the "Configurations" menu, while on prod we keep the fully customized menu.
=> Enable Configurations menu on DEV
