igdmapps/igdm

browser/css/login.css, browser/js/login.js, browser/login.html, main.js
This fixes issue #17 - Error message on entering invalid username/password
=> Add error message on login failure

browser/js/renderers.js
Addresses #35. Cool project @ifedapoolarewaju!
=> Add support for reel_share type

main/main.js
Just to decrease all those new users creating issues until 2FA is supported, took me a bit to figure out it wasn't my password that was wrong.
=> Warn 2fa not supported

main/instagram.js
Fixing session ID from "Users not following back" promise
=> Fixing "Users not following back"

package.json
Downgraded electron-builder version to 20.14.7
=> Electron-builder error.

browser/js/renderers.js
I've added a simple raven_media renderer to handle expiring photos.
=> add simple raven_media renderer

CONTRIBUTORS
Just want to remove my mention, that's all. Should be easy to merge
=> Contributors (1-line change)

browser/js/funcs.js, browser/js/renderers.js
added option to copy an image URL to clipboard on chat by right-clicking the picture
=> added ability to copy image URL to clipboard

browser/js/renderers.js
=> fix not able to contact new people

browser/css/app.css, browser/js/renderers.js
Render the received placeholders when the user is not allowed to see the post.
=> Render placeholder messages

browser/css/app.css, browser/js/funcs.js, browser/js/index.js, browser/js/renderers.js
This are some visual hints for the chatlist to differentiate between sent messages, seen+received messages and not-seen+received messages
=> Better ux for chatList

browser/css/app.css, browser/js/renderers.js
=> Fix up media

gulpfile.js, main/main.js, package-lock.json, package.json
Fixes #1166.
This includes https://github.com/igdmapps/igdm/pull/1170 so it should be merged first.
=> Add live reloading

browser/css/app.css
I've changed the close icon position to fixed. Sometimes it doesn't appear.
=> edit close icon position

browser/css/app.css, browser/js/funcs.js, browser/js/globals.js, browser/js/index.js, browser/js/renderers.js, main/instagram.js, main/main.js
Delete a conversation from chatList of Instagram DM.
Closes: #1078 
Steps: 
1. Select a conversation in the chatList and open the context menu by right clicking.
2. Click on **Delete this conversation**
3. Confirm the Delete by selecting **Delete** or cancel it by **Cancel**.
4. The conversation will get removed from the chat list.
_**Note: The conversation deleted will be removed from the DM Inbox of instagram.**_
=> [Feat] Delete a chat ( Contextmenu option )

browser/js/index.js, main/autolaunch.js, main/main.js, main/menutemplate.js, package-lock.json, package.json
Introducing a Menu-Item:
- Configurations
1. Auto-Launch ( type: checkbox )
**Functionality :** Configure the app to launch at System boot.
**Type:** Toggle switch to check and uncheck.
**Module** added in **_package.json_** : "auto-launch": "^5.0.5"
**Preview : **
=> [Feat] Run App on startup

browser/js/index.js, main/main.js
=> [Fix] Unexpected expansion of text area. 

browser/img/heart.svg, browser/js/renderers.js
**Issue:**
- The like message was rendered as a image with _context menus_.
- "_image/love.png_" file was treated like an image. 
- Captures a lot of chat area
**Preview:**
**Fix-Preview:**
=> [UI-Fix] Rendering a like message 

browser/css/app.css, browser/js/index.js, browser/js/renderers.js
**Task:**
Show Loading while fetching unfollowers from instagram API.
**Preview:**
Closes #1256
=> [Fix] LoadingGif() while loading unfollowers.

browser/.eslintrc.json, browser/css/app.css, browser/js/funcs.js, browser/js/index.js, browser/js/renderers.js
**UI-Issue:**
Currently in IGdm we don't show difference between a normal chat and a group chat in the chat-List.
**Fix**
We can show a group chat of any number of members with any 5 user's images in chat list..
**Preview:**
=> [UI-Fix] Group Chat in ChatList Rendering

browser/js/renderers.js, main/instagram.js, main/main.js
Hi y'all!
The purpose of this pull-request is to show info about the activity of the users, as it happens in the official app. These are my first steps with javascript, which means that there will surely be room for improvement, and I'm open to suggestions! 
Cheers!
=> User presence is now shown

browser/css/app.css, browser/js/renderers.js
Allow displaying of videos sent on chats
=> Added videos rendering

browser/js/renderers.js
Refactored the `renderImageOrVideo` function a bit, as we were defining the images twice. Also adding this function to the rendering of the user stories.
=> Refactor media function

browser/js/funcs.js, browser/js/renderers.js
Fixed the bug where we would constantly display the blue dot when the last "unread" message was actually a like from the other person. We will not show these non-valid messages on the chat list anymore as well.
=> Fixed notification for likes

browser/css/app.css, browser/js/funcs.js, browser/js/index.js, browser/js/renderers.js, package-lock.json, package.json
Similar to Instagram native client, we will display the date when the last message was sent on the chat list. A watcher will refresh the time every couple of seconds.
=> Display last message date on the list of chats

browser/css/app.css
Adding the time that media messages were sent.
=> adding time display to media content

browser/js/funcs.js, browser/js/renderers.js, package.json
This commit fixes image load of the users (avatar, profile pictures from dm, unfollowers and search)
=> Fixes image loads

browser/js/renderers.js
These changes fixes in chat image, video, audio media contents and liked avatar on the message.
=> Fixes message media contents [image video audio]

main/instagram.js, package.json
Fixes 404 issue when trying to login
Fix #1486 #1483 #1482 #1481 #1480 #1479 #1478 #1477 #1475 #1474 #1473 #1472 #1471 #1469 #1468 #1467 #1466 #1463 #1459 #1456
=> fix #1486 #1483 #1482 #1481 #1480 #1479 #1478 #1477 #1475 #1474 #1473 #1472 #1471 #1469 #1468 #1467 #1466 #1463 #1459 #1
